version: '3.8'

services:
  app:
    container_name: scraper-container
    image: aesbube/scraper:latest
    restart: unless-stopped
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/app   
    command: ["Scraper"] 